#!/bin/bash

# Inspired from https://github.com/matthewmccullough/dotfiles/blob/master/bash_gitprompt

        RED="\[\033[0;31m\]"
     YELLOW="\[\033[0;33m\]"
      GREEN="\[\033[0;32m\]"
       BLUE="\[\033[0;34m\]"
     PURPLE="\[\033[0;35m\]"
  LIGHT_RED="\[\033[1;31m\]"
LIGHT_GREEN="\[\033[1;32m\]"
      WHITE="\[\033[1;37m\]"
 LIGHT_GRAY="\[\033[0;37m\]"
 COLOR_NONE="\[\e[0m\]"

function parse_git_branch {
  git rev-parse --git-dir &> /dev/null
  git_status=`git status 2> /dev/null`
  branch_pattern="^# On branch ([^${IFS}]*)"
  remote_pattern="# Your branch is (.*) of"
  diverge_pattern="# Your branch and (.*) have diverged"

  if [[ ${git_status} =~ ${branch_pattern} ]]; then
    branch=${BASH_REMATCH[1]}

    if [[ ! ${git_status}} =~ "working directory clean" ]]; then
      if [[ ${git_status} =~ ${remote_pattern} ]]; then
        if [[ ${BASH_REMATCH[1]} == "ahead" ]]; then
          remote="↑"
        else
          remote="↓"
        fi
      fi
      if [[ ${git_status} =~ ${diverge_pattern} ]]; then
        remote="↕"
      fi
      echo " ${RED}(${branch} ${remote}⚡)${COLOR_NONE}"
    else
      echo " ${GREEN}(${branch})${COLOR_NONE}"
    fi
  fi
}

function prompt_func() {
  PS1="${PURPLE}\u${COLOR_NONE}@${GREEN}\h${COLOR_NONE}:${YELLOW}\w${COLOR_NONE}$(parse_git_branch)\n\$ "
}

PROMPT_COMMAND=prompt_func
